# Generated by Django 2.0 on 2020-08-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('PK_ROL', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=25)),
                ('ESTADO', models.BooleanField(default=True)),
            ],
        ),
    ]
