# Generated by Django 2.1 on 2020-10-24 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('pk_antecedente', models.AutoField(primary_key=True, serialize=False)),
                ('ultima_regla', models.DateTimeField()),
                ('fecha_probable_parto', models.DateTimeField()),
                ('gesta', models.DateTimeField()),
                ('aborto', models.DateTimeField()),
                ('hijos_vivos', models.IntegerField(blank=True, null=True)),
                ('peso', models.IntegerField(blank=True, null=True)),
                ('quirurgico', models.TextField(blank=True, null=True)),
                ('medico', models.TextField(blank=True, null=True)),
                ('alergia', models.TextField(blank=True, null=True)),
                ('familiar', models.TextField(blank=True, null=True)),
                ('habito', models.TextField(blank=True, null=True)),
                ('cigarro', models.BooleanField(default=False)),
                ('licor', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Antecedente',
                'verbose_name_plural': 'Antecedentes',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('pk_cita', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(null=True)),
                ('fecha', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('pk_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_consulta', models.CharField(max_length=200)),
                ('historia', models.TextField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['motivo_consulta'],
            },
        ),
        migrations.CreateModel(
            name='ControlClinica',
            fields=[
                ('pk_control_clinica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la clinica')),
                ('servicio', models.BooleanField(verbose_name='control atendiendo/no atendiendo')),
                ('estado', models.BooleanField(verbose_name='Activa/Desactivada')),
            ],
            options={
                'verbose_name': 'Control clinica',
                'verbose_name_plural': 'Controles clinicas',
            },
        ),
        migrations.CreateModel(
            name='Csat',
            fields=[
                ('pk_csat', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('fk_cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Cita')),
            ],
            options={
                'verbose_name': 'HistorialCsat',
                'verbose_name_plural': 'HistorialCsat',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('pk_examen_fisico', models.AutoField(primary_key=True, serialize=False)),
                ('presion_arterial', models.IntegerField(blank=True, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('frecuencia_respitaroria', models.IntegerField(blank=True, null=True)),
                ('temperatura', models.IntegerField(null=True)),
                ('frecuencia_cardiaca_fetal', models.IntegerField(blank=True, null=True)),
                ('impresion_clinica', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Examene Fisico',
                'verbose_name_plural': 'Examenes Fisicos',
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('pk_historial_clinico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('fk_antecendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Antecedente')),
                ('fk_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Consulta')),
                ('fk_examen_fisico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.ExamenFisico')),
            ],
            options={
                'verbose_name': 'Historial clinico',
                'verbose_name_plural': 'Historiales clinicos',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('pk_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('pk_persona', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('dpi', models.CharField(default='--MENOR DE EDAD--', max_length=14)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('genero', models.CharField(max_length=10)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_civil', models.CharField(blank=True, default='soltero', max_length=7, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fk_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Municipio')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['fecha_nacimiento'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('pk_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('pk_rol', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del rol')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre del rol')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado activo/incativo')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEstado',
            fields=[
                ('pk_tipo_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo estado',
                'verbose_name_plural': 'Tipos estados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('pk_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('carnet', models.CharField(max_length=60)),
                ('contrasena', models.CharField(max_length=25)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, default='nocorreo@dominio.com', max_length=254, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fk_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Persona')),
                ('fk_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='fk_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Persona'),
        ),
        migrations.AddField(
            model_name='csat',
            name='fk_pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Pregunta'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fk_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Persona'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fk_tipo_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinic.TipoEstado'),
        ),
    ]
