# Generated by Django 2.0 on 2020-08-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('PK_ESTADO_CIVIL', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=25)),
                ('ESTADO', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('PK_MUNICIPIO', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=25)),
                ('ESTADO', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
    ]
