# Generated by Django 2.0 on 2020-09-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Persona',
            name='DIRECCION',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
