# Generated by Django 2.1 on 2020-10-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='primer_apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='primer_nombre',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='segundo_nombre',
        ),
    ]
