# Generated by Django 2.0 on 2020-09-10 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='FK_PERSONA',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Persona'),
        ),
    ]
