# Generated by Django 2.0 on 2020-09-11 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclinico',
            name='FK_ANTECEDENTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Antecedente'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='FK_CONSULTA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Consulta'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='FK_EXAMEN_FISICO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.ExamenFisico'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='FK_PERSONA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Persona'),
        ),
    ]
