# Generated by Django 2.0 on 2020-09-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedente',
            name='GESTA_ACTUAL',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
