# Generated by Django 2.0 on 2020-09-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0002_antecedente_gesta_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedente',
            name='CIGARRO',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='antecedente',
            name='LICOR',
            field=models.BooleanField(default=False),
        ),
    ]
