# Generated by Django 2.0 on 2020-09-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0002_persona_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='FECHA_NACIMIENTO',
            field=models.DateField(),
        ),
    ]
