# Generated by Django 2.0 on 2020-09-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0002_auto_20200911_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='FK_PERSONA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Persona'),
        ),
    ]
