# Generated by Django 2.0 on 2020-09-11 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0002_auto_20200910_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='FK_TIPO_ESTADO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Clinic.TipoEstado'),
            preserve_default=False,
        ),
    ]
