# Generated by Django 2.0 on 2020-08-10 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0002_auto_20200810_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('PK_DIRECCION', models.AutoField(primary_key=True, serialize=False)),
                ('DESCRIPCION', models.TextField()),
                ('ESTADO', models.BooleanField(default=True)),
                ('FK_MUNICIPIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Municipio')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
            },
        ),
    ]
