# Generated by Django 2.0 on 2020-09-11 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0003_auto_20200911_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='FK_USUARIO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Clinic.Usuario'),
            preserve_default=False,
        ),
    ]
