# Generated by Django 2.0 on 2020-09-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0003_auto_20200904_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenfisico',
            name='IMPRESION_CLINCIA',
            field=models.TextField(),
        ),
    ]
