# Generated by Django 2.0 on 2020-09-11 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0003_cita_fk_tipo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='FK_TIPO_ESTADO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinic.TipoEstado'),
        ),
    ]
