# Generated by Django 2.0 on 2020-08-11 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0003_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('PK_PERSONA', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=50)),
                ('APELLIDO', models.CharField(max_length=50)),
                ('DPI', models.CharField(default='Menor de edad', max_length=14)),
                ('EDAD', models.IntegerField(max_length=3)),
                ('FECHA', models.DateField(auto_now_add=True)),
                ('TELEFONO', models.IntegerField(blank=True, max_length=9, null=True)),
                ('GENERO', models.CharField(max_length=10)),
                ('ESTADO', models.BooleanField(default=True)),
                ('FK_DIRECCION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Direccion')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['FECHA'],
            },
        ),
        migrations.AlterModelOptions(
            name='estadocivil',
            options={'ordering': ['NOMBRE'], 'verbose_name': 'Estado Civil', 'verbose_name_plural': 'Estados Civiles'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['NOMBRE'], 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['NOMBRE'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AddField(
            model_name='persona',
            name='FK_ESTADO_CIVIL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.EstadoCivil'),
        ),
    ]
