# Generated by Django 2.0 on 2020-09-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0004_remove_antecedente_gesta_actual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antecedente',
            old_name='GESTA_INICIO',
            new_name='GESTA',
        ),
    ]
