# Generated by Django 2.0 on 2020-08-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0004_auto_20200810_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='TELEFONO',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
