# Generated by Django 2.0 on 2020-09-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0004_historialclinico_fk_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialclinico',
            name='FK_USUARIO',
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='FILTRO_NOMBRE_COMPLETO',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
