# Generated by Django 2.1 on 2020-10-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0004_auto_20201027_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fk_tipo_estado',
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_estado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
