# Generated by Django 2.0 on 2020-09-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0005_auto_20200909_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antecedente',
            old_name='PK_ANTECEDENTES',
            new_name='PK_ANTECEDENTE',
        ),
    ]
