# Generated by Django 2.1 on 2020-09-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0005_auto_20200911_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlClinica',
            fields=[
                ('PK_CONTROL_CLINICA', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=200, verbose_name='Nombre de la clinica')),
                ('SERVICIO', models.BooleanField(verbose_name='control atendiendo/no atendiendo')),
            ],
        ),
    ]
