# Generated by Django 2.0 on 2020-08-11 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0005_auto_20200810_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('PK_PREGUNTA', models.AutoField(primary_key=True, serialize=False)),
                ('DESCRIPCION', models.CharField(max_length=200)),
                ('FECHA_CREACION', models.DateField(auto_now_add=True)),
                ('ESTADO', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['FECHA_CREACION'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('PK_USUARIO', models.AutoField(primary_key=True, serialize=False)),
                ('CARNET', models.CharField(max_length=60)),
                ('CONTRASENIA', models.CharField(max_length=25)),
                ('FECHA_CREACION', models.DateField(auto_now_add=True)),
                ('CORREO', models.EmailField(blank=True, default='nocorreo@dominio.com', max_length=254, null=True)),
                ('ESTADO', models.BooleanField(default=True)),
                ('FK_PERSONA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Persona')),
                ('FK_ROL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['FECHA_CREACION'],
            },
        ),
    ]
