# Generated by Django 2.1 on 2020-09-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0006_controlclinica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlclinica',
            options={'verbose_name': 'Control clinica', 'verbose_name_plural': 'Controles clnicas'},
        ),
        migrations.RenameField(
            model_name='controlclinica',
            old_name='NOMBRE',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='controlclinica',
            old_name='PK_CONTROL_CLINICA',
            new_name='pk_control_clinica',
        ),
        migrations.RenameField(
            model_name='controlclinica',
            old_name='SERVICIO',
            new_name='servicio',
        ),
    ]
