# Generated by Django 2.0 on 2020-08-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0006_pregunta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='EDAD',
            field=models.IntegerField(),
        ),
    ]
