# Generated by Django 2.0 on 2020-08-11 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0007_auto_20200811_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCsat',
            fields=[
                ('PK_HISTORIAL_CSAT', models.AutoField(primary_key=True, serialize=False)),
                ('RESPUESTA', models.IntegerField()),
                ('FECHA_CREACION', models.DateField(auto_now_add=True)),
                ('ESTADO', models.BooleanField(default=True)),
                ('FK_PREGUNTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Pregunta')),
            ],
            options={
                'verbose_name': 'HistorialCsat',
                'verbose_name_plural': 'HistorialCsat',
                'ordering': ['FECHA_CREACION'],
            },
        ),
        migrations.CreateModel(
            name='TipoCita',
            fields=[
                ('PK_TIPO_CITA', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=50)),
                ('ESTADO', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo Cita',
                'verbose_name_plural': 'Tipos Citas',
                'ordering': ['NOMBRE'],
            },
        ),
    ]
