# Generated by Django 2.1 on 2020-09-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0007_auto_20200925_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlclinica',
            name='estado',
            field=models.BooleanField(default=1, verbose_name='Activa/Desactivada'),
            preserve_default=False,
        ),
    ]
