# Generated by Django 2.1 on 2020-09-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0008_controlclinica_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlclinica',
            options={'verbose_name': 'Control clinica', 'verbose_name_plural': 'Controles clinicas'},
        ),
    ]
