# Generated by Django 2.0 on 2020-08-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0009_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('PK_CONSULTA', models.AutoField(primary_key=True, serialize=False)),
                ('MOTIVO_CONSULTA', models.CharField(max_length=200)),
                ('HISTORIA', models.TextField()),
                ('ESTADO', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['MOTIVO_CONSULTA'],
            },
        ),
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('PK_EXAMEN_FISICO', models.AutoField(primary_key=True, serialize=False)),
                ('PRESION_ARTERIAL', models.FloatField()),
                ('FRECUENCIA_CARDIACA', models.FloatField()),
                ('FRECUENCIA_RESPIRATORIA', models.FloatField()),
                ('TEMPERATURA', models.FloatField()),
                ('FRECUENCIA_CARDIACA_FETAL', models.FloatField()),
                ('IMPRESION_CLINCIA', models.CharField(max_length=200)),
                ('ESTADO', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Examene Fisico',
                'verbose_name_plural': 'Examenes Fisicos',
            },
        ),
    ]
