# Generated by Django 2.1 on 2020-11-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0010_auto_20201103_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedente',
            name='tipo_antecedente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examenfisico',
            name='tipo_examen_fisico',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
