# Generated by Django 2.0 on 2020-08-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0010_consulta_examenfisico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('PK_ANTECEDENTES', models.AutoField(primary_key=True, serialize=False)),
                ('ULTIMA_REGLA', models.DateTimeField(blank=True, null=True)),
                ('FECHA_PROBABLE_PARTO', models.DateTimeField(blank=True, null=True)),
                ('GESTA', models.DateTimeField(blank=True, null=True)),
                ('ABORTO', models.DateTimeField(blank=True, null=True)),
                ('HIJOS_VIVOS', models.IntegerField(blank=True, null=True)),
                ('PESO', models.FloatField(blank=True, null=True)),
                ('QUIRURGICO', models.TextField(blank=True, null=True)),
                ('MEDICO', models.TextField(blank=True, null=True)),
                ('ALERGIA', models.TextField(blank=True, null=True)),
                ('FAMILIAR', models.TextField(blank=True, null=True)),
                ('HABITO', models.TextField(blank=True, null=True)),
                ('CIGARRO', models.TextField(blank=True, null=True)),
                ('LICOR', models.TextField(blank=True, null=True)),
                ('ESTADO', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Antecedente',
                'verbose_name_plural': 'Antecedentes',
            },
        ),
    ]
