# Generated by Django 2.1 on 2020-11-04 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0012_auto_20201104_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclinico',
            name='fk_antecedente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinic.Antecedente'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='fk_consulta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinic.Consulta'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='fk_examen_fisico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinic.ExamenFisico'),
        ),
    ]
