# Generated by Django 2.1 on 2020-11-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0013_auto_20201104_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenfisico',
            name='temperatura',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
