# Generated by Django 2.1 on 2020-11-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0015_medicamento_recetario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='nombre',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True, verbose_name='Nombre del medicamento'),
        ),
    ]
