# Generated by Django 2.1 on 2020-11-06 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0018_auto_20201105_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nps',
            fields=[
                ('pk_nps', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('fk_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clinic.Pregunta')),
            ],
            options={
                'verbose_name': 'HistorialNps',
                'verbose_name_plural': 'HistorialNps',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.RemoveField(
            model_name='csat',
            name='fk_cita',
        ),
        migrations.RemoveField(
            model_name='csat',
            name='fk_pregunta',
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='fk_pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinic.Pregunta'),
        ),
        migrations.DeleteModel(
            name='Csat',
        ),
    ]
