# Generated by Django 2.1 on 2020-11-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0020_auto_20201105_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activa/Desactivada'),
        ),
    ]
