# Generated by Django 2.1 on 2020-11-06 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0023_auto_20201106_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialclinico',
            name='fk_pregunta',
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='fk_nps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinic.Nps'),
        ),
    ]
