# Generated by Django 2.1 on 2020-11-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0024_auto_20201106_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nps',
            name='respuesta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
