# Generated by Django 2.1 on 2020-11-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0025_auto_20201106_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_inicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='hora_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='hora_inicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='hora_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='hora_inicio',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
