# Generated by Django 2.1 on 2020-11-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0026_auto_20201106_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
