# Generated by Django 2.1 on 2020-11-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0027_auto_20201106_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='nombre',
            field=models.CharField(default=1, max_length=400, verbose_name='Nombre de paciente'),
            preserve_default=False,
        ),
    ]
