# Generated by Django 2.1 on 2020-11-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0028_historialclinico_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('pk_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('brev_descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='nps',
            options={'ordering': ['respuesta'], 'verbose_name': 'Nps', 'verbose_name_plural': 'Nps'},
        ),
    ]
