# Generated by Django 2.1 on 2020-11-09 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0029_auto_20201109_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['pk_consulta'], 'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='motivo_consulta',
        ),
        migrations.AddField(
            model_name='consulta',
            name='fk_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinic.Servicio'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='estado',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='historia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
