# Generated by Django 2.1 on 2020-11-10 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0031_auto_20201109_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlclinica',
            old_name='servicio',
            new_name='estado_servicio',
        ),
    ]
