# Generated by Django 2.1 on 2020-11-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0032_auto_20201110_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='hora_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
