# Generated by Django 2.1 on 2020-11-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0033_auto_20201118_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclinico',
            name='hora_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
